---
abstract: 'FFI::Platypus bindings for libpostal'
author:
  - 'Avishai Goldman <veesh@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test2::V0: '0'
  Test::LeakTrace: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Postal
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Geo::Postal::FFI:
    file: lib/Geo/Postal/FFI.pm
    version: '0.004'
  Geo::Postal::Preload:
    file: lib/Geo/Postal/Preload.pm
    version: '0.004'
  Geo::Postal::Structs:
    file: lib/Geo/Postal/Structs.pm
    version: '0.001'
  Geo::Postal::Structs::Duplicates:
    file: lib/Geo/Postal/Structs/Duplicates.pm
    version: '0.004'
  Geo::Postal::Structs::Expansions:
    file: lib/Geo/Postal/Structs/Expansions.pm
    version: '0.001'
  Geo::Postal::Structs::Hashes:
    file: lib/Geo/Postal/Structs/Hashes.pm
    version: '0.001'
  Geo::Postal::Structs::Parser:
    file: lib/Geo/Postal/Structs/Parser.pm
    version: '0.001'
  Geo::Postal::Structs::ParserResponse:
    file: lib/Geo/Postal/Structs/ParserResponse.pm
    version: '0.001'
requires:
  Encode::Simple: '0'
  Exporter::Tiny: '0'
  FFI::Platypus: '0'
  FFI::Platypus::Record::StringArray: '0'
  Import::Into: '0'
  Try::Tiny: '0'
version: '0.004'
x_Dist_Zilla:
  perl:
    version: '5.026001'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: '@Starter::Git/Git::GatherDir'
      version: '2.046'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Starter::Git/MetaYAML'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Starter::Git/MetaJSON'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Starter::Git/License'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::Pod2Readme
      name: '@Starter::Git/Pod2Readme'
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Starter::Git/PodSyntaxTests'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Starter::Git/Test::ReportPrereqs'
      version: '0.027'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: develop
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Starter::Git/Test::Compile'
      version: '2.058'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter::Git/MakeMaker'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Starter::Git/Manifest'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Starter::Git/PruneCruft'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Starter::Git/ManifestSkip'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter::Git/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.17.1
          repo_root: .
      name: '@Starter::Git/Git::Check'
      version: '2.046'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in:
            - /
          commit_msg: '%v%n%n%c'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.17.1
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Starter::Git/Release_Commit'
      version: '2.046'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: '0.004'
          tag_format: '%v'
          tag_message: '%v'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.17.1
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Starter::Git/Git::Tag'
      version: '2.046'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.17.1
          repo_root: .
      name: '@Starter::Git/Git::Push'
      version: '2.046'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Starter::Git/TestRelease'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Starter::Git/ConfirmRelease'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Starter::Git/UploadToCPAN'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Starter::Git/MetaConfig'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Starter::Git/MetaNoIndex'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Starter::Git/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.012'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '0'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000033'
          version: '0.006'
      name: '@Starter::Git/MetaProvides::Package'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Starter::Git/ShareDir'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Starter::Git/ExecDir'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: -Transformer
              version: '4.015'
      name: PodWeaver
      version: '4.008'
    -
      class: Dist::Zilla::Plugin::RewriteVersion
      config:
        Dist::Zilla::Plugin::RewriteVersion:
          add_tarball_name: 0
          finders:
            - ':ExecFiles'
            - ':InstallModules'
          global: 0
          skip_version_provider: 0
      name: RewriteVersion
      version: '0.018'
    -
      class: Dist::Zilla::Plugin::BumpVersionAfterRelease
      config:
        Dist::Zilla::Plugin::BumpVersionAfterRelease:
          finders:
            - ':ExecFiles'
            - ':InstallModules'
          global: 0
          munge_makefile_pl: 1
      name: BumpVersionAfterRelease
      version: '0.018'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: ~
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.17.1
          repo_root: .
      name: Git::CommitBuild
      version: '2.046'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Starter::Git/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.012'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.012'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
